[theme]
primaryColor = "#F63366"  # Cor principal da interface (opcional)
backgroundColor = "#FFFFFF"  # Cor do fundo branco
secondaryBackgroundColor = "#F0F0F5"  # Cor de fundo secundária (opcional)
textColor = "#000000"  # Cor do texto (preto, para contraste com o fundo branco)
